<?php

namespace App\Common;

final class FtpServiceResponseStatuses
{
	const SUCCESS = 'SUCCESS';
	const FILE_TYPE_NOT_SUPPORTED = 'FILE_TYPE_NOT_SUPPORTED';
	const FILE_NOT_RECEIVED = 'FILE_NOT_RECEIVED';
	const FILE_NOT_EXIST = 'FILE_NOT_EXIST';
	const STORAGE_FAILED = 'STORAGE_FAILED';
	const NOT_SAME_FILE_EXTENSION = 'NOT_SAME_FILE_EXTENSION';
	const SOMETHING_ELSE = 'SOMETHING_ELSE';
	const PERMISSION_DENIED = 'PERMISSION_DENIED';
	const ACC_NOT_FOUND = 'ACC_NOT_FOUND';
	const UPLOADFILEORDER_NOT_FOUND = 'UPLOADFILEORDER_NOT_FOUND';
}
